name: Pylint and tests

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
    - uses: actions/checkout@v3
    - name: Setting up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Installing dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint setuptools
    - name: Analysing the code with pylint
      run: |
        pylint --indent-string "\t" --disable=broad-except,bare-except,no-else-return $(git ls-files '*.py')
    - name: Running tests
      run: |
        python -c "import dcpim;help(dcpim)" > USAGE.txt
        python test.py
