name: Upload PyPi Package

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install setuptools twine
        pip install build
    - name: Update USAGE.txt
      run: python -c "import dcpim;help(dcpim.dcpim)" > USAGE.txt
    - name: Setup PyPi
      run: |
        echo "[pypi]" > ~/.pypirc
        echo "username=__token__" >> ~/.pypirc
        echo "password=${{ secrets.PYPI_TOKEN }}" >> ~/.pypirc
    - name: Build package
      run: python3 setup.py sdist
    - name: Publish package
      run: twine upload dist/*
